### ISSUE TITLE
change "I" to "we" in page below

### ISSUE THREAD

**Issue by Pittab** [ThisCatLikesCrypto/Website#8]
![Screenshot 2024-03-29 at 09 04 41](https://github.com/ThisCatLikesCrypto/Website/assets/120305267/8984a64b-b285-4b7b-baaf-29417722458d)

I would like this language, specifically "I" changed as I believe I also make a significant contribution to the game, you know, like writing the original html, css and javascript. And jasper since he helped me figure out gstelementbyid's for the game

**Comment by Pittab** [comment]
doing myself, just wanted to announce

**Comment by ThisCatLikesCrypto** [comment]
i added that to active-dev as well pls use active-dev in future thank you
